# Generated by Django 3.2.18 on 2023-05-08 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0002_auto_20230504_1714'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='adminlogin',
            new_name='login',
        ),
    ]
