# Generated by Django 3.2.18 on 2023-05-10 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0004_rename_login_adlogin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branchname', models.CharField(max_length=10)),
                ('description', models.TextField(max_length=100)),
                ('image', models.ImageField(default='null.jpg', upload_to='pic')),
            ],
        ),
        migrations.DeleteModel(
            name='Adlogin',
        ),
    ]
