# Generated by Django 3.2.18 on 2023-05-11 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0005_auto_20230510_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicename', models.CharField(max_length=10)),
                ('branchname', models.CharField(max_length=10)),
                ('price', models.CharField(max_length=10)),
                ('image', models.ImageField(default='null.jpg', upload_to='pic')),
            ],
        ),
    ]
