# Generated by Django 3.2.18 on 2023-05-14 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0009_auto_20230513_2247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='subservice',
            name='service_name',
        ),
        migrations.RemoveField(
            model_name='subservice',
            name='service_type',
        ),
        migrations.AddField(
            model_name='subservice',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subservice',
            name='name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subservice',
            name='services',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='Adminapp.service'),
        ),
    ]
