# Generated by Django 3.2.18 on 2023-05-15 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0011_alter_subservice_services'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Services',
        ),
        migrations.AddField(
            model_name='service',
            name='service_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='service',
            name='service_type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='SubService',
        ),
    ]
