# Generated by Django 3.2.18 on 2023-05-21 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=10)),
                ('email1', models.EmailField(max_length=254)),
                ('message1', models.CharField(max_length=1000)),
            ],
        ),
    ]
