# Generated by Django 3.2.18 on 2023-05-24 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email1',
            field=models.EmailField(default=0, max_length=254),
        ),
    ]
