# Generated by Django 3.2.18 on 2023-05-30 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userapp', '0004_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
    ]
