# Generated by Django 3.2.18 on 2023-05-30 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0012_auto_20230515_1302'),
        ('Userapp', '0006_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='serviceid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Adminapp.service'),
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.TimeField(default=0),
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
