# Generated by Django 3.2.18 on 2023-05-30 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Userapp', '0007_auto_20230530_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='serviceid',
        ),
        migrations.AddField(
            model_name='booking',
            name='cartid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Userapp.cart'),
        ),
        migrations.AddField(
            model_name='booking',
            name='userid',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='Userapp.register'),
        ),
        migrations.AddField(
            model_name='cart',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.IntegerField(),
        ),
    ]
