# Generated by Django 3.2.18 on 2023-05-31 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Userapp', '0010_auto_20230531_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='cartid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Userapp.cart'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='userid',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='Userapp.register'),
        ),
    ]
